[zsh] Clean functions

diff --git a/functions/dotfail b/functions/dotfail
--- a/functions/dotfail
+++ b/functions/dotfail
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 dotfail () {
-  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
-  echo ''
-  exit 1
+    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "${1}"
+    echo ''
+    exit 1
 }
